# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/0783c16f-b242-4d60-ad0b-5fc3fba35d58";
    fsType = "btrfs";
    options = ["subvol=@"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/8BD7-860A";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/0783c16f-b242-4d60-ad0b-5fc3fba35d58";
    fsType = "btrfs";
    options = ["subvol=@home"];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/0783c16f-b242-4d60-ad0b-5fc3fba35d58";
    fsType = "btrfs";
    options = ["subvol=@nix"];
  };

  fileSystems."/opt" = {
    device = "/dev/disk/by-uuid/0783c16f-b242-4d60-ad0b-5fc3fba35d58";
    fsType = "btrfs";
    options = ["subvol=@opt"];
  };

  fileSystems."/.snapshots" = {
    device = "/dev/disk/by-uuid/0783c16f-b242-4d60-ad0b-5fc3fba35d58";
    fsType = "btrfs";
    options = ["subvol=@snapshots"];
  };

  fileSystems."/.swap" = {
    device = "/dev/disk/by-uuid/0783c16f-b242-4d60-ad0b-5fc3fba35d58";
    fsType = "btrfs";
    options = ["subvol=@swap"];
  };

  fileSystems."/var" = {
    device = "/dev/disk/by-uuid/0783c16f-b242-4d60-ad0b-5fc3fba35d58";
    fsType = "btrfs";
    options = ["subvol=@var"];
  };

  swapDevices = [
    {
      device = "/.swap/swapfile";
      size = 8 * 1024;
    }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
