import = [
    "~/.config/alacritty/themes/catppuccin-mocha.toml",
    "~/.config/alacritty/local.toml",
]

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "ExtraBold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "ExtraBold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "SemiBold Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Medium"

[window.padding]
y = 4
x = 6

[env]
TERM = "xterm-256color"

[shell]
program = "zsh"
args = ["-l", "-c", "tmux new-session -A -s main -c $HOME"]
